##Main configuration file for MiningWorld
##Author TheKrinKer


##This is the main configuration options
##Flat bedrock (true/false) whether the plugin should generate bedrock as a flat layer or vanilla style with noise
Config:
  Flat Bedrock: false

##This is where you set the properties for the materials/ores
##Radius - This defines the maximum size of the vein
##Rarity - The chance of the ore spawning
Ores:
  DIRT:
    radius: 60
    rarity: 70
  GRAVEL:
    radius: 75
    rarity: 80
  GRANITE:
    radius: 55
    rarity: 80
  DIORITE:
    radius: 5
    rarity: 80
  ANDESITE:
    radius: 5
    rarity: 80
  COAL_ORE:
    radius: 10
    rarity: 93
  DIAMOND_ORE:
    radius: 7
    rarity: 25
  EMERALD_ORE:
    radius: 4
    rarity: 15
  REDSTONE_ORE:
    radius: 9
    rarity: 88
  GOLD_ORE:
    radius: 5
    rarity: 65
  LAPIS_ORE:
    radius: 7
    rarity: 88
  IRON_ORE:
    radius: 7
    rarity: 80
  COPPER_ORE:
    radius: 6
    rarity: 85
  ANCIENT_DEBRIS:
    radius: 3
    rarity: 5
  NETHER_QUARTZ_ORE:
    radius: 9
    rarity: 70