name: MiningWorld
version: 1.2.2
api-version: 1.21
description: Mining world generation plugin
author: TheKrinKer
main: com.thekrinker.MiningWorld
load: STARTUP
commands:
  mwreload:
    description: Reloads the Mining World configuration file.
    usage: /<command>
    permission: miningworld.reload